GET https://rickandmortyapi.com/api/character

###
GET https://rickandmortyapi.com/api/character/?page=2

###
GET https://rickandmortyapi.com/api/episode/10

###
GET https://rickandmortyapi.com/api/character/21

###
GET https://rickandmortyapi.com/api/character/1,183,3

###
GET https://rickandmortyapi.com/api/character/?name=Toxi

###
GET https://rickandmortyapi.com/api/character/?origin:{name:"Ea"}